name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 1.38.40
          actions-cache-folder: 'emsdk-cache'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install Packages
        shell: bash
        run: |
          sudo apt-get install --fix-missing libgl1-mesa-dev  
          pip3 install jinja2
      - name: Configure CMake
        run: >
          emcmake cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DBUILD_EXAMPLES=ON \
          -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cd ${{ github.workspace }}/build
          emmake make -j 6
