name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 ## DO NOT FORGET THE CHECKOUT ACTION!!!! :D
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 1.38.40
          actions-cache-folder: 'emsdk-cache'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install Packages
        shell: bash
        run: |
          sudo apt-get install --fix-missing libgl1-mesa-dev  
          pip3 install jinja2 setuptools
      - name: Configure CMake
        run: >
          emcmake cmake -B ${{ github.workspace }}/build-ems -DBUILD_EXAMPLES=ON \
          -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cd ${{ github.workspace }}/build-ems
          emcc --clear-ports
          emmake make VERBOSE=1 -j 6
